

"""
Storytelling Web Application for Kids (Aged 3-10)
------------------------------------------------
This application processes an uploaded image, generates a 50-100 word child-friendly 
story based on the visual contents using Hugging Face Transformers pipelines, 
and converts the text to audio speech using gTTS.
"""

import io
import streamlit as st
from PIL import Image
from transformers import pipeline
from gtts import gTTS


# ==============================================================================
# STAGE 1: MODEL INITIALIZATION & CACHING
# ==============================================================================
@st.cache_resource
def load_caption_model():
    """
    Loads the BLIP Image Captioning pipeline.
    Uses @st.cache_resource to prevent re-downloading/re-loading on every user interaction.
    """
    return pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )

@st.cache_resource
def load_story_model():
    """
    Loads a lightweight text generation pipeline (GPT-2) optimized for speed on Streamlit Cloud.
    """
    return pipeline(
        "text-generation",
        model="gpt2"
    )


# ==============================================================================
# STAGE 2: CORE MODULAR FUNCTIONS
# ==============================================================================
def image_to_text(image: Image.Image, caption_pipeline) -> str:
    """
    Extracts descriptive caption text from an input PIL image using BLIP.
    
    Args:
        image (Image.Image): Uploaded user image.
        caption_pipeline: Pre-loaded Hugging Face image-to-text pipeline.
        
    Returns:
        str: Descriptive caption text.
    """
    try:
        results = caption_pipeline(image)
        if results and len(results) > 0:
            return results[0]['generated_text']
        return "a magical scene full of colors"
    except Exception as err:
        st.error(f"Error during image processing: {err}")
        return "a magical scene full of colors"


def text_to_story(caption: str, story_pipeline) -> str:
    """
    Expands the image caption into a 50-100 word child-friendly story.
    
    Args:
        caption (str): Image caption generated by BLIP.
        story_pipeline: Pre-loaded Hugging Face text-generation pipeline.
        
    Returns:
        str: Complete 50-100 word child-friendly narrative.
    """
    prompt = f"Once upon a time, in a happy and bright magical land, there was {caption}. "
    
    try:
        # Generation bounds tuned for fast inference and target word length
        output = story_pipeline(
            prompt,
            max_new_tokens=110,
            min_new_tokens=60,
            do_sample=True,
            top_k=50,
            top_p=0.92,
            temperature=0.8,
            pad_token_id=50256,
            num_return_sequences=1
        )
        
        raw_story = output[0]['generated_text']
        
        # Clean and split into sentences to ensure sensible length bounds
        sentences = raw_story.replace('\n', ' ').split('. ')
        valid_sentences = []
        word_count = 0
        
        for sentence in sentences:
            clean_s = sentence.strip()
            if not clean_s:
                continue
            if not clean_s.endswith('.'):
                clean_s += '.'
            
            valid_sentences.append(clean_s)
            word_count += len(clean_s.split())
            
            # Target range: approximately 50-100 words
            if word_count >= 55:
                break
                
        final_story = " ".join(valid_sentences)
        
        # Add friendly ending suited for children
        if not final_story.endswith("The end!"):
            final_story += " Everyone smiled and had a wonderful day. The end!"
            
        return final_story

    except Exception as err:
        st.error(f"Error during story generation: {err}")
        return f"Once upon a time, there was {caption}. They went on a joyful adventure and made many new friends. The end!"


def story_to_speech(story_text: str) -> io.BytesIO:
    """
    Converts the generated story text into an MP3 audio stream using gTTS.
    
    Args:
        story_text (str): Narrative text to be spoken.
        
    Returns:
        io.BytesIO: In-memory byte buffer containing the MP3 audio.
    """
    tts = gTTS(text=story_text, lang='en', slow=False)
    audio_buffer = io.BytesIO()
    tts.write_to_fp(audio_buffer)
    audio_buffer.seek(0)
    return audio_buffer


# ==============================================================================
# STAGE 3: MAIN APPLICATION & USER INTERFACE
# ==============================================================================
def main():
    """
    Main application orchestrator and Streamlit UI definition.
    """
    # Streamlit page layout configuration
    st.set_page_config(
        page_title="Magic Picture Storyteller 🎨✨",
        page_icon="🦄",
        layout="centered"
    )

    # Custom kid-friendly CSS styling
    st.markdown("""
        <style>
        .main {
            background-color: #f0f8ff;
        }
        h1 {
            color: #ff4b4b;
            font-family: 'Comic Sans MS', cursive, sans-serif;
            text-align: center;
        }
        .stButton>button {
            background-color: #ff8c00;
            color: white;
            font-size: 20px;
            font-weight: bold;
            border-radius: 12px;
            width: 100%;
            height: 3em;
        }
        </style>
    """, unsafe_allow_html=True)

    st.title("🌟 Magic Picture Storyteller 📖")
    st.write("Welcome, Little Explorer! Upload a picture to hear a magic story made just for you!")

    # Sidebar documentation & instructions
    with st.sidebar:
        st.header("🎈 How to Play")
        st.write("1. Click below or drag a picture file into the upload box.")
        st.write("2. Press the **'🚀 Tell Me a Story!'** button.")
        st.write("3. Read and press Play to hear your audio story!")
        st.info("Designed for children aged 3–10.")

    # Model initialization with progress indicator
    with st.spinner("Loading AI models... Please wait a moment."):
        caption_pipe = load_caption_model()
        story_pipe = load_story_model()

    # Image Uploader (supports drag-and-drop or file browsing)
    uploaded_file = st.file_uploader(
        "Upload your picture here:",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:
        try:
            # Display uploaded image preview
            image = Image.open(uploaded_file).convert("RGB")
            
            col1, col2 = st.columns([1, 1])
            with col1:
                st.subheader("🖼️ Your Picture")
                st.image(image, use_container_width=True)

            with col2:
                st.subheader("✨ Story Time")
                
                if st.button("🚀 Tell Me a Story!"):
                    # 1. Process image to caption
                    with st.spinner("Looking closely at your picture..."):
                        caption = image_to_text(image, caption_pipe)
                        st.caption(f"**Image detail detected:** *\"{caption}\"*")

                    # 2. Expand caption to story
                    with st.spinner("Writing your magic story..."):
                        story = text_to_story(caption, story_pipe)

                    st.success("Story Complete!")
                    st.markdown(f"> **{story}**")

                    # Display word count for assignment compliance verification
                    word_count = len(story.split())
                    st.caption(f"📏 Story Length: **{word_count} words**")

                    # 3. Convert story to speech audio
                    with st.spinner("Creating audio voice..."):
                        audio_data = story_to_speech(story)
                        st.subheader("🔊 Listen to Your Story")
                        st.audio(audio_data, format="audio/mp3")

        except Exception as e:
            st.error(f"Failed to load image: {e}")


# Program execution entry point
if __name__ == "__main__":
    main()
